# Generated by Django 5.1.6 on 2025-02-08 16:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='images/', verbose_name='фото иконки')),
            ],
            options={
                'verbose_name': 'Блок "почему мы?"',
                'verbose_name_plural': 'Блок "почему мы?"',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nad_title', models.CharField(max_length=30, verbose_name='Над заголовок')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('little_title', models.CharField(max_length=100, verbose_name='Под заголовок')),
                ('click_button', models.CharField(help_text='https://t.me/afina_fabric', max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='WhoWe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='images/', verbose_name='фото №1')),
                ('img2', models.ImageField(upload_to='images/', verbose_name='фото №2')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('desc', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Блок "кто мы?"',
                'verbose_name_plural': 'Блок "кто мы?"',
            },
        ),
    ]
