# Generated by Django 5.1.6 on 2025-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_slider_little_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whowe',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото №2'),
        ),
    ]
