# Generated by Django 5.1.6 on 2025-02-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_whowe_img2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='nad_title',
            new_name='on_title',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='little_title',
            new_name='under_title',
        ),
        migrations.RemoveField(
            model_name='whowe',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='whowe',
            name='img2',
        ),
        migrations.AddField(
            model_name='slider',
            name='button_title',
            field=models.CharField(default='Связаться', max_length=30, verbose_name='Имя кнопки'),
        ),
        migrations.AddField(
            model_name='whowe',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото'),
        ),
    ]
