# Generated by Django 5.1.6 on 2025-02-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_nad_title_slider_on_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Баннер'),
        ),
    ]
