# Generated by Django 5.1.6 on 2025-02-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_settings_phone1_alter_settings_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
