# Generated by Django 5.1.6 on 2025-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_settings_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='whowe',
            name='on_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Над заголовок'),
        ),
        migrations.AddField(
            model_name='whowe',
            name='under_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Под заголовок'),
        ),
    ]
