# Generated by Django 5.1.6 on 2025-02-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_whowe_on_title_whowe_under_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts_for_stages_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/', verbose_name='фото')),
                ('cart_title', models.CharField(max_length=100, verbose_name='Заголовок для карточки')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'карточка для этапа работы',
                'verbose_name_plural': 'Карточки для этапов работы',
            },
        ),
        migrations.CreateModel(
            name='Stages_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_title', models.CharField(max_length=100, verbose_name='Над заголовок')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
            },
        ),
    ]
