# Generated by Django 5.1.6 on 2025-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_carts_for_stages_of_work_stages_of_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='фото')),
                ('title', models.CharField(max_length=100, verbose_name='Обозначение')),
            ],
            options={
                'verbose_name': 'галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Text_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_title', models.CharField(max_length=100, verbose_name='Над заголовок')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст для галереи',
                'verbose_name_plural': 'Текста для галереи',
            },
        ),
    ]
