# Generated by Django 5.1.6 on 2025-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_gallery_text_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_gallery',
            name='under_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Под заголовок'),
        ),
    ]
